site_name: "GCC Photo Vote"
site_title: "Photography Contest 2025"
submission_forms_url: "https://forms.gle/your-form-id-submit"
voting_forms_url: "https://forms.gle/your-form-id-voting"
deadlines:
  submit_open: "2025-08-21 14:30:00" 
  submit_close: "2025-08-21 16:00:00" 
  voting_open: "2025-08-25 9:00:00"
  voting_close: "2025-08-25 19:00:00"
  # Optional: set the time when the results link/button should appear
  # If not set and show_results is true, results will show immediately after voting ends
  # If show_results is false, nothing related to results will be shown
  results: "2025-08-30 20:00:00"
show_countdown: all # voting, submission, all or none
show_gallery: voting # Only enabled in Voting phase. voting, submission, all or none. Set to none to hide carousel and gallery cards. 
show_voting: true # Set to false to hide the vote button
show_results: false # Set to true to show results button after voting ends
hide_team_data: true # Set to true to hide team names and show rank based on a 'final' column
footer:
  text: "© 2025 (BCA) NeoTech Club, GCC"
  mono_link: "https://mono.layogtima.com/"
