site_name: "GCC Photo Vote"
site_title: "Photography Contest 2025"
forms_url: "https://forms.gle/your-form-id"
deadlines:
  open: "2025-08-24 10:00:00"
  close: "2025-08-24 19:00:00"
show_countdown: true
hide_team_data: true # Set to true to hide team names and show rank based on a 'final' column
footer:
  text: "Made by (BCA) NeoTech Club © 2025"
  mono_link: "https://mono.layogtima.com/"
