site_name: "GCC Photo Vote"
site_title: "GCC Photography Contest"
forms_url: "https://forms.gle/your-form-id"
deadlines:
  open: "2025-08-22 09:00:00"
  close: "2025-08-30 17:00:00"
show_countdown: true
hide_team_data: false # Set to true to hide team names and show rank based on a 'final' column
footer:
  text: "Made by (BCA) NeoTech Club © 2025"
  mono_link: "https://mono.layogtima.com/"
